name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./